name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
    types: [ opened, edited, synchronize, reopened ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: |
        make init
    - name: Force xcode 14
      run: |
        sudo xcode-select -switch /Applications/Xcode_14.app
    - name: Build
      run: |
        make build
#    - name: SPM Build
#      run: |
#        make spm_build
#    - name: Test
#      run: |
#        make test
    - name: documentation
      if: github.ref == 'refs/heads/master'
      run: |
        make doc
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: evgenyVasilev
        author_email: ctrateg13@gmail.com
        message: "Updates for documentation"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
